Handle player action choices
dataforgoodfr/offseason_ogre pull request #104
Opened 2022-07-11 16:59 UTC by Baboo7

- ticket: https://ogre-d4g.atlassian.net/browse/D4G-65

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/15690915/180478776-3d71a416-ed3b-4e61-91ab-850678ecea68.png">

2022-07-11 17:05 UTC, Baboo7 commented
C'est une PR intermédiaire pour valider avec vous la récupération des actions

2022-07-12 15:01 UTC, remiriv commented on packages/server/src/modules/actions/controllers/index.ts
> +  const stepActions = await services.getMany(step);
On pourrait renommer getMany en getAllSteps

2022-07-12 15:01 UTC, remiriv commented on packages/server/src/modules/websocket/eventHandlers/updatePlayerActionsHandler.ts
> +        ?.split("=")[1] || ""
on pourrait utiliser une lib pour parser les cookies ici 
https://stackoverflow.com/questions/33316013/node-js-socket-io-get-cookie-value
https://www.npmjs.com/package/cookie

2022-07-12 15:01 UTC, remiriv commented on packages/server/src/modules/users/services/authenticateUser.ts
> +  let email: string | undefined;
pourquoi le definir en let ici et pas directement en const en dessous?

2022-07-12 15:01 UTC, remiriv commented on packages/server/src/modules/users/services/authenticateUser.ts
> +  let email: string | undefined;
ah oui ok pour le try catch

2022-07-12 15:01 UTC, remiriv commented on packages/client/src/modules/play/playerActions/Actions.tsx
>    children?: JSX.Element;
à enlever si y a plus la prop

2022-07-12 15:01 UTC, remiriv commented
@Baboo7 quelques commentaires mais sur le fonctionnement global ça a l'air nickel et pas trop galère comme ça c'est cool!!

2022-07-13 09:29 UTC, Baboo7 commented on packages/client/src/modules/play/playerActions/Actions.tsx
>    children?: JSX.Element;
Bien vu !

2022-07-13 09:44 UTC, Baboo7 commented on packages/server/src/modules/actions/controllers/index.ts
> +  const stepActions = await services.getMany(step);
`getMany` est pour moi pertinent comme on récupère plusieurs `action`s en les filtrant par `step`

2022-07-16 15:41 UTC, louis-sanna-eki commented on packages/client/src/modules/play/playerActions/Actions.tsx
> +  }, []);
@Baboo7 comme le dit github, c'est mieux de préserver la réactivité avec un tableau de deps.

2022-07-16 15:41 UTC, louis-sanna-eki commented on packages/client/src/modules/play/playerActions/Actions.tsx
> +            isPerformed={playerAction.isPerformed}
@Baboo7 [détail] on passer directement player action en prop.

2022-07-16 15:44 UTC, louis-sanna-eki commented on packages/client/src/modules/play/context/playContext.tsx
> +    socket.emit("updatePlayerActions", { update: { playerActions } });
@Baboo7 on update pas l'état dans le context donc la ça va pas mettre à jour pour les autres joueurs non?

2022-07-18 10:07 UTC, Baboo7 commented on packages/client/src/modules/play/playerActions/Actions.tsx
> +            isPerformed={playerAction.isPerformed}
Je pense que ça rend le composant très dépendant de la donnée où `action` doit faire partie de `playerAction`. On peut partir là dessus et voir ce que ça donne dans la durée

2022-07-18 10:09 UTC, Baboo7 commented on packages/client/src/modules/play/context/playContext.tsx
> +    socket.emit("updatePlayerActions", { update: { playerActions } });
L'action met seulement à jour les actions du joueur en base sans dispatcher le nouvel état aux autres joueurs, ni même à l'animateur. C'était bien ta question ?

2022-07-20 10:45 UTC, louis-sanna-eki commented on packages/client/src/modules/play/context/playContext.tsx
> +    socket.emit("updatePlayerActions", { update: { playerActions } });
@Baboo7 oui. Si c'est ce qu'on veut go.

2022-07-22 16:06 UTC, Baboo7 commented
J'ai pas mal changé le code depuis la dernière review, je vous conseille de lire les fichiers modifiés dans l'ensemble plutôt que par commit.
La raison est que côté front les player actions étaient récupérées par appel REST et mises à jour par websocket. Ça m'a pas mal posé de problème pour déclencher le rafraichissement des données après update par websoket. Maintenant les player actions sont gérées uniquement par appel REST et ça marche bien mieux.

Aussi, maintenant le nombre de PA utilisé est màj en temps réel côté user.

2022-07-25 14:47 UTC, remiriv commented
> J'ai pas mal changé le code depuis la dernière review, je vous conseille de lire les fichiers modifiés dans l'ensemble plutôt que par commit. La raison est que côté front les player actions étaient récupérées par appel REST et mises à jour par websocket. Ça m'a pas mal posé de problème pour déclencher le rafraichissement des données après update par websoket. Maintenant les player actions sont gérées uniquement par appel REST et ça marche bien mieux.
> 
> Aussi, maintenant le nombre de PA utilisé est màj en temps réel côté user.

@Baboo7 le fait de ne plus utiliser de websocket ça va pas compliquer pas mal la mise à jour du budget et des PA du joueur sur l'interface admin? Ou alors il faudrait envoyer un message via websocket quand l'utilisateur update une action pour que le refresh se fasse côté admin?

2022-07-25 17:41 UTC, Baboo7 commented
Hmm c'est vrai que côté animateur ça complique la chose

2022-07-26 14:10 UTC, louis-sanna-eki commented
> La raison est que côté front les player actions étaient récupérées par appel REST et mises à jour par websocket. Ça m'a pas mal posé de problème pour déclencher le rafraichissement des données après update par websoket. Maintenant les player actions sont gérées uniquement par appel REST et ça marche bien mieux.

Et si on faisait tout en websocket comme pour l'état du jeu, ça marcherai pas?

2022-07-28 22:20 UTC, Baboo7 commented
Oui c'est ce je vais faire. Ça va permettre de notifier l'animateur par la même

2022-08-01 19:31 UTC, Baboo7 commented
Les players actions sont maintenant màj par websocket

2022-08-01 21:10 UTC, louis-sanna-eki commented
@Baboo7 je regarde ça demain.

2022-08-04 14:59 UTC, louis-sanna-eki commented
@Baboo7 dsl de mon manque de réactivité. Je te promet je fais une review ce week-end.

2022-08-04 16:36 UTC, Baboo7 commented
@louis-sanna-eki pas de trouble c'est les vacs 👌

2022-08-07 20:31 UTC, louis-sanna-eki requested changes
@Baboo7 ça m'a l'air très bien!

En revanche l'état des actions n'est pas partagé entre tabs, je ne sais pas pourquoi.

<img width="1800" alt="Screenshot 2022-08-07 at 22 29 06" src="https://user-images.githubusercontent.com/85956496/183309943-8adc06e7-c72e-4be6-a22c-35118759abbb.png">

2022-08-07 20:31 UTC, louis-sanna-dev commented on packages/client/src/modules/play/playerActions/Actions.tsx
> +            isPerformed={playerAction.isPerformed}
ok

2022-08-07 20:31 UTC, louis-sanna-eki commented on packages/client/src/modules/play/context/playContext.tsx
> +  useGameSocket,
@Baboo7 pas besoin de l'exporter la socket, c'est même mieux de cacher l'implémentation.

2022-08-08 20:45 UTC, Baboo7 commented on packages/client/src/modules/play/context/playContext.tsx
> +  useGameSocket,
C'est un résidu de test, bien vu

2022-08-08 20:47 UTC, Baboo7 commented on packages/client/src/modules/play/context/playContext.tsx
> +  useGameSocket,
Concernant la mise à jour entre les tabs, tu parles du tab joueur et du tab animateur ? Pour le moment y'a que le tab du joueur qui est mis à jour comme les player actions updatées ne sont pas broadcastées mais simplement retournées à l'émetteur

2022-08-08 21:59 UTC, Baboo7 commented on packages/client/src/modules/play/context/playContext.tsx
> +  useGameSocket,
Feedback traités

2022-08-09 11:30 UTC, louis-sanna-eki approved these changes
@Baboo7 good! 🚀

2022-08-09 17:43 UTC, merged