Features/#24 create crud
dataforgoodfr/offseason_ogre pull request #11
Opened 2022-01-11 21:27 UTC by remi-boivin

## Proposed changes
---

Add player, carConsumption and planeConsumption crud 

## Types of changes
---
What types of changes does your code introduce to ogre ?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe):

## Checklist
---
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation and modify the README.md (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules
- [x] If the feature changes current behavior, reasons why your solution is better.

2022-01-12 15:46 UTC, Vladou73 requested changes

2022-01-12 15:46 UTC, Vladou73 commented on server/app/utils/autoresources.js
> +            console.log('=================>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: ' + routename);
we should maybe also print `route[core]`, because for now waht appears in console looks like duplicates
This is what I get below in terminal:
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /players
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /players
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /players/:id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /players/:id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /players/:id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /carconsumptions
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /carconsumptions
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /carconsumptions/:id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /carconsumptions/:id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /carconsumptions/:id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /planeconsumptions
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /planeconsumptions
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /planeconsumptions/:id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /planeconsumptions/:id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: /planeconsumptions/:id
```

2022-01-12 15:46 UTC, Vladou73 commented on server/app/utils/autoresources.js
> +            var routename = mapping.action == 'index' ? '/' + name : mapping.action == 'create' ? '/' + name : '/' + name + '/' + params;
maybe for refacto in February it will be better to use [switch syntax](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/switch) or "if else" syntax, because this syntaxe with imbricated ternaire is very confusing

2022-01-12 15:46 UTC, Vladou73 commented on server/.env~
> +# port pour lancer l'application backend
Could you please tell me why you added this file ? is it a mistake or is it something usefull ? there is already a file `.env.example` to show what configs should be

2022-01-12 15:46 UTC, Vladou73 commented on server/app/controllers/carConsumptionController.js
> +carConsumptionController.show = async(_, response, next) => {
although it is working, I think `async(_, response, next)` should be `async(request, response, next)` as you are using the request parameters and passing them to `ressourceController`

2022-01-12 15:46 UTC, Vladou73 commented on server/app/controllers/carConsumptionController.js
> +    ressourceController.show(_, response, next, CarConsumption);
same here,  `ressourceController.show(_, response, next, CarConsumption)` should be changed to  `ressourceController.show(request, response, next, CarConsumption);`
This shows that the data coming from the request is used in the controller

2022-01-12 15:46 UTC, Vladou73 commented on server/app/controllers/carConsumptionController.js
> +carConsumptionController.create = async(_, response, next) => {
same here

2022-01-12 15:46 UTC, Vladou73 commented on server/app/controllers/carConsumptionController.js
> +carConsumptionController.update = async(_, response, next) => {
same here

2022-01-12 15:46 UTC, Vladou73 commented on server/app/controllers/carConsumptionController.js
> +carConsumptionController.destroy = async(_, response, next) => {
same here

2022-01-12 15:46 UTC, Vladou73 commented on server/app/controllers/carConsumptionController.js
> +carConsumptionController.index = async(_, response, next) => {
This is the only controller where there is no data coming with request object, we just send back all the data we have about cars, so it's fine to let `async(_, response, next)`

2022-01-12 15:46 UTC, Vladou73 commented on server/app/controllers/planeConsumptionController.js
> +const PlaneConsumption = require('../db/models/PlaneConsumption');
same comments as in `carConsumptionController.js`

2022-01-12 15:46 UTC, Vladou73 commented on server/app/controllers/playerController.js
>  const { Player, PlaneConsumption } = require('../db/models');
same comments as in `carConsumptionController.js`

2022-01-16 18:23 UTC, remi-boivin commented on server/app/utils/autoresources.js
> +            console.log('=================>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: ' + routename);
no it's the routes. There is nothing before (except the ip)

2022-01-16 18:23 UTC, remi-boivin commented on server/app/utils/autoresources.js
> +            var routename = mapping.action == 'index' ? '/' + name : mapping.action == 'create' ? '/' + name : '/' + name + '/' + params;
Okay I'll do it

2022-01-16 18:24 UTC, remi-boivin commented on server/.env~
> +# port pour lancer l'application backend
It's an error

2022-01-18 13:31 UTC, Vladou73 commented on server/app/utils/autoresources.js
> +            console.log('=================>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> map route: ' + routename);
ok but for instance what is the difference between the 2 first lines ?what is the difference between lines 3 to 5 ?

2022-01-18 13:32 UTC, Vladou73 approved these changes

2022-01-18 13:33 UTC, merged