Redirect players
dataforgoodfr/offseason_ogre pull request #156
Opened 2022-09-23 16:01 UTC by remiriv

2022-09-23 17:25 UTC, louis-sanna-eki commented on packages/server/src/modules/websocket/eventHandlers/updateGameHandler.ts
> +            hasFinishedStep: hasGameFinishedStep,
@remiriv pourquoi on envoie ça au client? Il a tout pour le calculer lui même non?

2022-09-23 17:27 UTC, louis-sanna-eki commented on packages/client/src/modules/play/utils/persona.ts
>      return personaBySteps[stepUsed];
@remiriv [remark] je sais que c'était déjà comme ça donc ne changeons pas dans cette PR, mais c'est quand même super bizarre de renvoyer le personna d'un persona precedent.

2022-09-23 17:29 UTC, louis-sanna-eki commented on packages/server/src/modules/websocket/eventHandlers/updateGameHandler.ts
> +      const hasPreviousGameFinishedStep = hasFinishedStep(gameUpdated);
@remiriv c'est deux fois la même chose?

2022-09-23 17:33 UTC, louis-sanna-eki commented on packages/client/src/modules/games/utils.ts
> +  return game.step === game.lastFinishedStep;
@remiriv je pense que qu'on veille accepter un partial, ça va renvoyer des valeurs fausses s'ils manque un des deux champs.

Pour le cas des setters on peut faire:

```
const new  = { ...previous, ...update };
hasFinishedStep(new);
```

2022-09-23 18:37 UTC, remiriv commented on packages/server/src/modules/websocket/eventHandlers/updateGameHandler.ts
> +            hasFinishedStep: hasGameFinishedStep,
C'est côté joueur donc c'est pour forcer le fait que c'est fini 
C'est la variable qui est aussi mise à jour quand il clique sur terminer le tour par exemple c'est pas du 100% calculé j'ai l'impression

2022-09-23 18:39 UTC, remiriv commented on packages/server/src/modules/websocket/eventHandlers/updateGameHandler.ts
> +      const hasPreviousGameFinishedStep = hasFinishedStep(gameUpdated);
Ah oui bien vu! le deuxième c'étiat pas la bonne variable

2022-09-23 18:46 UTC, Baboo7 requested changes
Un point important dans le `playContext`, le reste est top 👍

2022-09-23 18:46 UTC, Baboo7 commented on packages/client/src/modules/games/utils.ts
> +  return game.step === game.lastFinishedStep;
Ça pourrait être une valeur retournée par le hook `usePlay`

2022-09-23 18:46 UTC, Baboo7 commented on packages/client/src/modules/play/context/playContext.tsx
> +            navigate(`/play/games/${previous.id}/persona`);
Le fait qu'on ne redirige que les joueurs n'est pas évident. Ça peut le faire dans un premier temps

2022-09-23 18:46 UTC, Baboo7 commented on packages/client/src/modules/play/context/playContext.tsx
> +    pathname,
Ça va poser problème d'ajouter `pathname`. Le problème de ce `useEffect` est qu'une nouvelle socket est créée à chaque fois qu'une dépendance change. Pour avoir testé ça crée une fuite de mémoire comme les sockets précédentes ne sont pas fermées

2022-09-23 18:46 UTC, Baboo7 commented on packages/client/src/modules/play/utils/persona.ts
> +      step > game.lastFinishedStep ? game.lastFinishedStep : step;
Tellement plus simple ❤️

2022-09-23 19:51 UTC, louis-sanna-eki commented on packages/client/src/modules/play/context/playContext.tsx
> +    pathname,
En fait je comprends pas la fonctionnalité, mais le faut l'extraire de la construction de la socket à proprement dit.

```js
  const navigate = useNavigate();
  const { pathname } = useLocation();
  useEffect(() => {
    if (
      gameWithTeams &&
      gameWithTeams?.status !== "finished" &&
      gameWithTeams?.status === "finished"
    ) {
      navigate("/play");
    }
    if (
      gameWithTeams &&
      hasFinishedStep(gameWithTeams) &&
      !hasFinishedStep(gameWithTeams) &&
      pathname.endsWith("actions")
    ) {
      navigate(`/play/games/${gameWithTeams.id}/persona`);
    }
  }, [gameWithTeams, navigate, pathname]);
```

2022-09-24 08:57 UTC, louis-sanna-eki commented on packages/client/src/modules/play/context/playContext.tsx
> +    pathname,
Et si on besoin de la valeur précédent on peut faire un usePrevious

https://usehooks.com/usePrevious/

2022-09-27 09:48 UTC, remiriv commented on packages/client/src/modules/play/context/playContext.tsx
> +            navigate(`/play/games/${previous.id}/persona`);
Oui il faudrait peut être à terme plutôt envoyer un autre message à toutes les teams pour dire que c'est fini

2022-09-27 09:56 UTC, remiriv commented on packages/client/src/modules/play/context/playContext.tsx
> +    pathname,
En fait la fonctionnalité c'est de forcer la redirection des joueurs sur la page d'accueil du jeu quand l'animateur clique sur le bouton pour terminer l'étape 
Donc là ce que je veux faire c'est à la réception d'un message `gameUpdated`, dans le cas où ça correspond à un passage de l'étape de `En cours` à `Terminé` -> Si l'utilisateur est sur la page d'actions, le rediriger sur la page persona, sinon si il est sur une autre page (genre les stats) ne rien faire

2022-09-27 09:58 UTC, remiriv commented on packages/client/src/modules/play/context/playContext.tsx
> +    pathname,
Après on peut dans un premier temps considérer que quelle que soit la page sur laquelle est le joueur on le renvoie sur la page persona (ou stats d'ailleurs ça aurait du sens), et comme ça ça permettrait d'enlever la dépendance à pathname

2022-09-27 10:19 UTC, louis-sanna-eki commented on packages/client/src/modules/play/context/playContext.tsx
> +    pathname,
@remiriv 
> En fait la fonctionnalité c'est de forcer la redirection des joueurs sur la page d'accueil du jeu quand l'animateur clique sur le bouton pour terminer l'étape Donc là ce que je veux faire c'est à la réception d'un message `gameUpdated`, dans le cas où ça correspond à un passage de l'étape de `En cours` à `Terminé` -> Si l'utilisateur est sur la page d'actions, le rediriger sur la page persona, sinon si il est sur une autre page (genre les stats) ne rien faire

OK. Un useEffect devrait effectivement marcher.

Un truc du genre:

```js
useEffect(() => { navigate("/persona") }, [isGameFinished, navigate])
```

2022-09-27 10:36 UTC, remiriv commented on packages/client/src/modules/play/context/playContext.tsx
> +    pathname,
j'ai fait la modif dans le dernier commit en enlevant la référence à pathname tu me dis si c'est good pour toi !

2022-09-27 10:53 UTC, louis-sanna-eki approved these changes
@remiriv LGTM!

2022-09-27 11:14 UTC, merged