Setup
dataforgoodfr/offseason_ogre pull request #26
Opened 2022-03-25 06:43 UTC by Brams75

Installation de husky, lint-staged, eslint, prettier, react-router, material-ui.

2022-03-26 18:37 UTC, louis-sanna-eki approved these changes
Good!

Juste une question sur le linter, je suis pas sur comprendre ce que fait le script.

2022-03-26 18:37 UTC, louis-sanna-eki commented on client/package.json
> +    "eject": "craco eject",
@Brams75 [question]  pourquoi a-t-on besoin de Craco ici?

2022-03-26 18:37 UTC, louis-sanna-eki commented on client/package.json
> +    "lint": "eslint .",
@Brams75 j'ai l'impression que cette commande ne fait rien. Pourtant ça m'a l'air bon.

<img width="430" alt="Screenshot 2022-03-26 at 19 36 07" src="https://user-images.githubusercontent.com/85956496/160252759-d38d8bb3-99f9-457f-bcdd-d81fdd6eb44a.png">
<img width="527" alt="Screenshot 2022-03-26 at 19 36 22" src="https://user-images.githubusercontent.com/85956496/160252760-d30b69c5-1898-44d6-b387-fd7bdcf491cb.png">

2022-03-26 19:09 UTC, Brams75 commented on client/package.json
> +    "eject": "craco eject",
J'avais installé craco pour faire des alias path, au lieu de faire import Hello from '../../../Hello', on fait juste import '@/Hello'.
Ca fonctionne bien, sauf que le linter me met une erreur. L'import fonctionne bien mais je ne l'avais pas encore réussi le réglé.

2022-03-31 08:15 UTC, louis-sanna-eki requested changes
waiting for fix

2022-04-03 19:07 UTC, louis-sanna-eki commented on client/package.json
> +    "eject": "craco eject",
@Brams75 en fait je pense que ça serait plus simple d'utiliser les paths typescript.

https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

Je pense que ça marche sans Craco. (à checker celà dit).

2022-04-04 19:33 UTC, louis-sanna-eki commented on client/package.json
> +    "eject": "craco eject",
Ah en fait je crois que tu as raison, CRA ne supporte pas les paths TS par défaut.

2022-04-06 11:31 UTC, closed without merging