feat: Add button to copy players emails to clipboard
dataforgoodfr/offseason_ogre pull request #274
Opened 2023-05-23 12:48 UTC by remiriv

### Changes

Ticket - https://ogre-d4g.atlassian.net/browse/D4G-282

### Remarks

2023-05-23 17:50 UTC, Baboo7 requested changes
Est ce que t'as testé de coller les valeurs dans gmail ?

2023-05-23 17:50 UTC, Baboo7 commented on packages/client/src/modules/administration/Games/Game/GamePlayers.tsx
> +  const retrieveEmails = useMutation<
Utilise plutôt `useQuery` comme l'action ne fait que récupérer des données

2023-05-23 17:50 UTC, Baboo7 commented on packages/client/src/modules/administration/Games/Game/GamePlayers.tsx
> +        navigator.clipboard.writeText(emails.join(t("admin.email.separator")));
Dans le `emails.join` mets plutôt le symbol `;` directement comme il ne dépend pas de la langue de l'utilisateur

2023-05-23 17:50 UTC, Baboo7 commented on packages/client/src/modules/translations/resources/fr/common.json
> +  "admin.email.separator": ";",
Cette traduction sera à supprimer

2023-05-24 07:19 UTC, remiriv commented on packages/client/src/modules/administration/Games/Game/GamePlayers.tsx
> +        navigator.clipboard.writeText(emails.join(t("admin.email.separator")));
yes ça marche, j'avais hésité en me disant que ça dépendant peut être des langues, mais je modifie

2023-05-24 07:40 UTC, remiriv commented
@Baboo7 j'ai fait les modifs ! et yes j'ai testé dans gmail ça marche nickel !

2023-05-24 19:14 UTC, Baboo7 approved these changes
Une typo à corriger et tu peux merger librement 👌

2023-05-24 19:14 UTC, Baboo7 commented on packages/client/src/modules/translations/resources/fr/common.json
> +  "message.success.admin.copied-emails": "La liste des adresse emails a été copiée dans le presse-papiers.",
Typo : `adresse` => `adresses`

2023-05-24 21:52 UTC, merged