Plane config
dataforgoodfr/offseason_ogre pull request #3
Opened 2021-12-22 11:31 UTC by Vladou73

- creation of model PlaneConfiguration (class + properties and methods)
- plane constants added in OGREConstants.js
- API route to retrieve data in DB from table plane_configuration

2022-01-02 11:13 UTC, remi-boivin requested changes

2022-01-02 11:13 UTC, remi-boivin commented on server/app/OGREConstants.js
> +    get CONSUMPTION_BY_PASSENGER() {
You should remove new line after the function

2022-01-02 11:13 UTC, remi-boivin commented on server/app/OGREConstants.js
>  //     CALORIFIC_VALUE: 10,
You must remove commented code. It's dirty to commit commented code

2022-01-02 11:13 UTC, remi-boivin commented on server/app/mocked_players.js
> +// planeConfig1.computeEnergyConsumptionPerDay();
Same here you need to remove commented code

2022-01-02 11:13 UTC, remi-boivin commented on server/app/mocked_players.js
> +
You may remove a new line

2022-01-02 11:13 UTC, remi-boivin commented on server/app/mocked_players.js
>  // first mock
I don't sure the comment is useful. Maybe you should either remove it or details it

2022-01-02 11:13 UTC, remi-boivin commented on server/app/controllers/playerController.js
> +        response.json(planeConfigs);
We should check if we found data and return either a success or a error message with corresponding status code

2022-01-02 11:13 UTC, remi-boivin commented on server/app/models/PlaneConfiguration.js
> +                // on transforme la donnée brute de la query sql en instance de PlaneConfiguration
Please translate the comment into English for a better understanding

2022-01-02 11:13 UTC, remi-boivin commented on server/app/OGREConstants.js
> +    }
Good work

2022-01-02 11:13 UTC, remi-boivin commented on server/app/models/PlaneConfiguration.js
> +const db = require('../database');
You need to change the path. database is in config folder

2022-01-03 20:25 UTC, Vladou73 commented
this pull request is outdated. It has been replaced by the pull request #8

2022-01-03 20:25 UTC, closed without merging